name: publish

on:
    workflow_dispatch: # Allow manual trigger
    release:
        types: [created]

jobs:
    publish-sardinecan:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Get version
              run: |
                  echo "VERSION=$(cat VERSION.txt)" >> $GITHUB_ENV

            - name: Build the SardineCan Docker image
              run: |
                  echo "Building SardineCan docker in ${{ env.VERSION }}"
                  echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                  export LATEST_TAG="ghcr.io/merschformann/sardinecan:latest"
                  export VERSION_TAG="ghcr.io/merschformann/sardinecan:${{ env.VERSION }}"
                  docker buildx build --platform linux/amd64,linux/arm64 --push -t $LATEST_TAG -t $VERSION_TAG -f Dockerfile ..
              working-directory: ./SC.Service
